/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "C:\\Users\\Dennis\\Documents\\GitHub\\doc\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-043dc38e",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-043dc38e").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-32596d55",
    path: "/pixelIt/software.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-32596d55").then(next)
    },
  },
  {
    name: "v-1c320f9a",
    path: "/pixelIt/api.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1c320f9a").then(next)
    },
  },
  {
    name: "v-63b1a36c",
    path: "/pixelIt/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-63b1a36c").then(next)
    },
  },
  {
    path: "/pixelIt/index.html",
    redirect: "/pixelIt/"
  },
  {
    name: "v-52588093",
    path: "/pixelIt/hardware.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-52588093").then(next)
    },
  },
  {
    path: '*',
    component: GlobalLayout
  }
]