/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "Vuepress Docs Boilerplate",
  "description": "",
  "base": "/",
  "headTags": [
    [
      "meta",
      {
        "name": "theme-color",
        "content": "#3eaf7c"
      }
    ],
    [
      "meta",
      {
        "name": "apple-mobile-web-app-capable",
        "content": "yes"
      }
    ],
    [
      "meta",
      {
        "name": "apple-mobile-web-app-status-bar-style",
        "content": "black"
      }
    ]
  ],
  "pages": [
    {
      "title": "Config",
      "frontmatter": {
        "sidebar": "auto"
      },
      "regularPath": "/config/",
      "relativePath": "config/README.md",
      "key": "v-3e4af544",
      "path": "/config/",
      "headers": [
        {
          "level": 2,
          "title": "foo",
          "slug": "foo"
        },
        {
          "level": 2,
          "title": "bar",
          "slug": "bar"
        }
      ]
    },
    {
      "title": "Introduction",
      "frontmatter": {},
      "regularPath": "/guide/",
      "relativePath": "guide/README.md",
      "key": "v-d6e137e4",
      "path": "/guide/"
    },
    {
      "title": "Using Vue in Markdown",
      "frontmatter": {},
      "regularPath": "/guide/using-vue.html",
      "relativePath": "guide/using-vue.md",
      "key": "v-01361333",
      "path": "/guide/using-vue.html",
      "headers": [
        {
          "level": 2,
          "title": "Browser API Access Restrictions",
          "slug": "browser-api-access-restrictions"
        },
        {
          "level": 2,
          "title": "",
          "slug": ""
        }
      ]
    },
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "https://v1.vuepress.vuejs.org/hero.png",
        "tagline": null,
        "actionText": "Quick Start →",
        "actionLink": "/guide/",
        "features": [
          {
            "title": "Feature 1 Title",
            "details": "Feature 1 Description"
          },
          {
            "title": "Feature 2 Title",
            "details": "Feature 2 Description"
          },
          {
            "title": "Feature 3 Title",
            "details": "Feature 3 Description"
          }
        ],
        "footer": "Made by Dennis Rathjen with ❤️"
      },
      "regularPath": "/",
      "relativePath": "index.md",
      "key": "v-043dc38e",
      "path": "/"
    }
  ],
  "themeConfig": {
    "repo": "",
    "editLinks": false,
    "docsDir": "",
    "editLinkText": "",
    "lastUpdated": false,
    "nav": [
      {
        "text": "Guide",
        "link": "/guide/"
      },
      {
        "text": "Config",
        "link": "/config/"
      },
      {
        "text": "VuePress",
        "link": "https://v1.vuepress.vuejs.org"
      }
    ],
    "sidebar": {
      "/guide/": [
        {
          "title": "Guide",
          "collapsable": false,
          "children": [
            "",
            "using-vue"
          ]
        }
      ]
    }
  }
}