/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "Bastelbunkers Dokumentation",
  "description": "Bastelbunkers Dokumentation",
  "base": "/",
  "headTags": [
    [
      "meta",
      {
        "name": "theme-color",
        "content": "#3eaf7c"
      }
    ],
    [
      "meta",
      {
        "name": "apple-mobile-web-app-capable",
        "content": "yes"
      }
    ],
    [
      "meta",
      {
        "name": "apple-mobile-web-app-status-bar-style",
        "content": "black"
      }
    ]
  ],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "https://v1.vuepress.vuejs.org/hero.png",
        "tagline": null,
        "actionText": "Pixel It",
        "actionLink": "/pixelit/",
        "footer": "Made by Dennis Rathjen with ❤️"
      },
      "regularPath": "/",
      "relativePath": "index.md",
      "key": "v-043dc38e",
      "path": "/"
    },
    {
      "title": "Software",
      "frontmatter": {},
      "regularPath": "/pixelIt/software.html",
      "relativePath": "pixelIt/software.md",
      "key": "v-32596d55",
      "path": "/pixelIt/software.html",
      "headers": [
        {
          "level": 2,
          "title": "Firmware Flashen",
          "slug": "firmware-flashen"
        },
        {
          "level": 3,
          "title": "Downloads:",
          "slug": "downloads"
        },
        {
          "level": 2,
          "title": "Nach dem Flashen",
          "slug": "nach-dem-flashen"
        }
      ]
    },
    {
      "title": "API",
      "frontmatter": {},
      "regularPath": "/pixelIt/api.html",
      "relativePath": "pixelIt/api.md",
      "key": "v-1c320f9a",
      "path": "/pixelIt/api.html",
      "headers": [
        {
          "level": 2,
          "title": "Beschreibung eines Screen",
          "slug": "beschreibung-eines-screen"
        }
      ]
    },
    {
      "title": "Einleitung",
      "frontmatter": {},
      "regularPath": "/pixelIt/",
      "relativePath": "pixelIt/index.md",
      "key": "v-63b1a36c",
      "path": "/pixelIt/",
      "headers": [
        {
          "level": 2,
          "title": "Vorteile",
          "slug": "vorteile"
        },
        {
          "level": 2,
          "title": "Benötigte Hardware",
          "slug": "benotigte-hardware"
        }
      ]
    },
    {
      "title": "Hardware",
      "frontmatter": {},
      "regularPath": "/pixelIt/hardware.html",
      "relativePath": "pixelIt/hardware.md",
      "key": "v-52588093",
      "path": "/pixelIt/hardware.html",
      "headers": [
        {
          "level": 2,
          "title": "Teileliste",
          "slug": "teileliste"
        },
        {
          "level": 2,
          "title": "Aufbau",
          "slug": "aufbau"
        },
        {
          "level": 2,
          "title": "3D Druck Dateien",
          "slug": "_3d-druck-dateien"
        }
      ]
    }
  ],
  "themeConfig": {
    "sidebar": [
      {
        "title": "Pixel It",
        "path": "/pixelIt",
        "collapsable": false,
        "sidebarDepth": 1,
        "children": [
          "/pixelIt/software",
          "/pixelIt/hardware",
          "/pixelIt/api"
        ]
      }
    ]
  }
}